version: "3"
services:
    frontend:
        deploy:
            replicas: 2
            placement:
                constraints: [node.role == manager]
    backend:
        deploy:
            replicas: 2
            placement:
                constraints: [node.role == manager]
    mongo:
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
