---
- name: Check && install python
  hosts: all
  become: true
  gather_facts: false
  vars:
    app_root: ../sample_html_site
    document_root: /var/www/html
  
  roles:
    - nginx

  tasks:
    - name: Copy website files to the server's document root
      synchronize:
        src: "{{ app_root }}/"
        dest: "{{ document_root }}"
        checksum: yes
        times: no
        delete: yes
      tags: deploy
